service: nexus-multiagent
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 2048
  timeout: 30
functions:
  cognitiveAnalyst:
    handler: handlers/cognitive.analyst
    events:
      - http:
          path: v1/cognitive
          method: post
  etlParser:
    handler: handlers/etl.parser
    events:
      - http:
          path: v1/etl
          method: post
plugins:
  - serverless-offline
